### ISSUE TITLE
Hitting <enter> does not do anything

### ISSUE THREAD

**Issue by jvandemo** [SamVerschueren/alfred-ng2#5]
Thanks for this workflow!

I followed the installation instructions and I see the `ng2` workflow in Alfred, but it doesn't seem to do anything when I type `ng2` and `<enter>`:

<img width="584" alt="schermafbeelding 2016-09-12 om 04 20 22" src="https://cloud.githubusercontent.com/assets/1859381/18423325/5107165a-78a4-11e6-8b8b-89e77a6e0b57.png">

When I hit `<enter>`, nothing happens.

Node: v6.1.0
Alfred: v3.1 [718]

Any idea what I may am missing?

**Comment by SamVerschueren** [comment]
Type a search query after hitting enter ;)

**Comment by jvandemo** [comment]
Brilliant&mdash;now it works like a charm! 👍 

I was mislead by the README, which says: "In Alfred, type ng2, Enter, and your query."

Thanks for making this workflow @SamVerschueren, works really well now 👍

**Comment by SamVerschueren** [comment]
Feedback on how it can be improved is always welcome.

**Comment by jvandemo** [comment]
I think the sentence:

"In Alfred, type `ng2` followed by your query and then hit enter"

would be more correct than:

"In Alfred, type ng2, Enter, and your query."

because I typed "ng2" and then hit enter and nothing happened, so I thought something was wrong.

If no one else had problems getting it to work, then I'm probably your dumbest user ever so you can safely ignore my thoughts :-)

**Comment by SamVerschueren** [comment]
> If no one else had problems getting it to work, then I'm probably your dumbest user ever so you can safely ignore my thoughts :-)

LOL! I must admit that I had the same problem with @sindresorhus his `alfred-npms` workflow. So we should definitely change that...

> because I typed "ng2" and then hit enter and nothing happened

It autocompletes if you'd only typed `ng` and it also adds a space :)

**Comment by jvandemo** [comment]
How about an animated gif as the perfect documentation? ;-)

![alfred-ng2](https://cloud.githubusercontent.com/assets/1859381/18427804/ac4a29d2-78ca-11e6-9617-be3aecda45c2.gif)
